{
  "formatVersion": "1.1",
  "component": {
    "group": "org.testng",
    "module": "testng",
    "version": "7.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "com.beust",
          "module": "jcommander",
          "version": {
            "requires": "1.82"
          }
        }
      ],
      "files": [
        {
          "name": "testng-7.7.0.jar",
          "url": "testng-7.7.0.jar",
          "size": 1004293,
          "sha512": "328dbc5384d5cf5daa85f7d65520894db5d1f27f50a81e37d7d0af38e55d9d8821843ba3024a8598bc873e49d5c74fa7593d79943e7dc5aac56e6a685c61f4e1",
          "sha256": "7c686ba8696f8206473b1b78e7e4947191b2aa4891c57b184b44ad4e052d2c08",
          "sha1": "5298a6662b94d9ee438b95a2d44ea3ac6ce2cb8e",
          "md5": "41996f05d63f72e49eee3ae7c5cb6231"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "com.beust",
          "module": "jcommander",
          "version": {
            "requires": "1.82"
          }
        },
        {
          "group": "org.webjars",
          "module": "jquery",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "testng-7.7.0.jar",
          "url": "testng-7.7.0.jar",
          "size": 1004293,
          "sha512": "328dbc5384d5cf5daa85f7d65520894db5d1f27f50a81e37d7d0af38e55d9d8821843ba3024a8598bc873e49d5c74fa7593d79943e7dc5aac56e6a685c61f4e1",
          "sha256": "7c686ba8696f8206473b1b78e7e4947191b2aa4891c57b184b44ad4e052d2c08",
          "sha1": "5298a6662b94d9ee438b95a2d44ea3ac6ce2cb8e",
          "md5": "41996f05d63f72e49eee3ae7c5cb6231"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "testng-7.7.0-javadoc.jar",
          "url": "testng-7.7.0-javadoc.jar",
          "size": 1170885,
          "sha512": "136635aff3a635afcbf4b742239981ccc1ecb60063313b8e5ac9aa5f4416cc23fffa59773fe2da9f65bb0be692ccdfd24f56eed668724a38255f6c0784bfb798",
          "sha256": "44258974dbf42fe6a2e3e20f49064fd81b244e4ef57b8c445789c37367782e9e",
          "sha1": "d26b5dda46a75178c830bdbd282cc080cd2da890",
          "md5": "462d56e501be3af6d7d1ddba938bcfe4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "testng-7.7.0-sources.jar",
          "url": "testng-7.7.0-sources.jar",
          "size": 499609,
          "sha512": "5c7a74ded079df01c0e6483f1772a3b6d11e5d15c0d0101e620f4edc3b6029c042cec713a02c9858654619d4a341cde46f71e82f35b0eea08c491ab4641fc757",
          "sha256": "28122c6c6acc444843185246602e4270b7400884cfcce748839a42d10acd50d3",
          "sha1": "966cfce163561e9c0c050cd33852073e8c5d6089",
          "md5": "cfffcd29b1043c9468e6359aa2a90f1c"
        }
      ]
    },
    {
      "name": "antApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.12"
          }
        }
      ],
      "capabilities": [
        {
          "group": "org.testng",
          "name": "testng-ant",
          "version": "7.7.0"
        }
      ]
    },
    {
      "name": "antRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.apache.ant",
          "module": "ant",
          "version": {
            "requires": "1.10.12"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "com.beust",
          "module": "jcommander",
          "version": {
            "requires": "1.82"
          }
        },
        {
          "group": "org.webjars",
          "module": "jquery",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "capabilities": [
        {
          "group": "org.testng",
          "name": "testng-ant",
          "version": "7.7.0"
        }
      ]
    },
    {
      "name": "guiceApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice-bom",
          "version": {
            "requires": "5.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.1.0"
          }
        }
      ],
      "capabilities": [
        {
          "group": "org.testng",
          "name": "testng-guice",
          "version": "7.7.0"
        }
      ]
    },
    {
      "name": "guiceRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.inject",
          "module": "guice-bom",
          "version": {
            "requires": "5.1.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.google.inject",
          "module": "guice",
          "version": {
            "requires": "5.1.0"
          }
        }
      ],
      "capabilities": [
        {
          "group": "org.testng",
          "name": "testng-guice",
          "version": "7.7.0"
        }
      ]
    },
    {
      "name": "junitApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "capabilities": [
        {
          "group": "org.testng",
          "name": "testng-junit",
          "version": "7.7.0"
        }
      ]
    },
    {
      "name": "junitRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "junit",
          "module": "junit",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "capabilities": [
        {
          "group": "org.testng",
          "name": "testng-junit",
          "version": "7.7.0"
        }
      ]
    },
    {
      "name": "yamlApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "capabilities": [
        {
          "group": "org.testng",
          "name": "testng-yaml",
          "version": "7.7.0"
        }
      ]
    },
    {
      "name": "yamlRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.33"
          }
        }
      ],
      "capabilities": [
        {
          "group": "org.testng",
          "name": "testng-yaml",
          "version": "7.7.0"
        }
      ]
    }
  ]
}
